version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build: ./api
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: ./api
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    command: celery -A app.celery_app:celery_app worker --loglevel=INFO --concurrency=1

  web:
    build: ./web
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

volumes:
  redis-data:
